name: codesafari
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_otp_text_field: ^1.1.3+2
  flutter_tts: ^4.0.2
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  line_awesome_flutter: ^3.0.1
  liquid_swipe: ^3.1.0
  permission_handler: ^11.3.1
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  smooth_page_indicator: ^1.2.0+3
  logger: ^1.1.0
  get_storage: ^2.0.3
  flutter_faq:
  tap_to_expand: ^0.7.2
  chat_bubbles: ^1.6.0
  flutter_dotenv:
  image:
  path_provider:
  mime:
  speech_to_text:
  google_speech: ^4.0.0
  grpc:
  picovoice_flutter:
  cheetah_flutter: ^2.0.1
  device_preview: ^1.2.0

  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/Petit Cochon.ttf
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_images/
    - assets/logo/
    - assets/images/story/
    - assets/images/forget_password/forget_password.png
    - assets/images/profile/profile_pic.png
    - .env

  fonts:
    - family: PetitCochon
      fonts:
        - asset: assets/fonts/Petit Cochon.ttf
